export const booksTypes = [
  { title: 'Все книги', count: '', category: 'all', testid: 'navigation-books' },
  { title: 'Бизнес книги', count: '8', category: 'business' },
  { title: 'Детективы', count: '14', category: 'detective' },
  { title: 'Зарубежная литература', count: '2', category: 'children' },
  { title: 'История', count: '5', category: 'history' },
  { title: 'Классическая литература', count: '12', category: 'classic' },
  { title: 'Книги по психологии', count: '11', category: 'psychology' },
  { title: 'Компьютерная литература', count: '54', category: 'computers' },
  { title: 'Культура и искусство', count: '5', category: 'culture' },
  { title: 'Наука и образование', count: '2', category: 'science' },
  { title: 'Публицистическая литература', count: '0', category: 'publicistic' },
  { title: 'Справочники', count: '10', category: 'references' },
  { title: 'Фантастика', count: '12', category: 'scifi' },
  { title: 'Юмористическая литература', count: '8', category: 'humor' },
];
